import {
  User,
  Users,
  UsersFour,
  UsersThree,
  Handshake,
  Baby,
  Student,
  GraduationCap,
  IdentificationBadge,
  Certificate,
  PencilRuler,
  Palette,
  PaintBrush,
  Ruler,
  Pen,
  Crop,
  Image,
  PictureInPicture,
  Camera,
  FilmSlate,
  MagicWand,
  Briefcase,
  Suitcase,
  Buildings,
  Presentation,
  PresentationChart,
  ChartLine,
  ChartLineUp,
  ChartBar,
  ChartPie,
  Target,
  Trophy,
  Rocket,
  Lightbulb,
  Strategy,
  Kanban,
  Calendar,
  Clipboard,
  Note,
  Files,
  Folder,
  Code,
  Terminal,
  Cpu,
  Desktop,
  Laptop,
  Database,
  CloudCheck,
  GitBranch,
  Bug,
  Robot,
  Wrench,
  Gear,
  Circuitry,
  Plug,
  WifiHigh,
  ChatCircle,
  Chat,
  Envelope,
  Megaphone,
  Broadcast,
  Phone,
  Headset,
  Video,
  Microphone,
  SpeakerHigh,
  Globe,
  Storefront,
  ShoppingBag,
  ShoppingCart,
  Bank,
  Wallet,
  CreditCard,
  Coin,
  Coins,
  Money,
  Receipt,
  Truck,
  Van,
  Airplane,
  Package,
  Scales,
  Handbag,
  Factory,
  Recycle,
  Leaf,
  Tree,
  Heart,
  Star,
  Sparkle,
  Compass,
  MapPin,
  Flag,
  Anchor,
  Hammer,
  Toolbox,
  Cube,
  Gift,
  Balloon,
  Confetti,
  Books,
  BookOpen,
} from '@phosphor-icons/react'

export const TEAM_COLOR_PALETTE = [
  { id: 'amber', light: '#FBEDD0', dark: '#D39A00' },
  { id: 'blue', light: '#E5F4FF', dark: '#0091FF' },
  { id: 'red', light: '#FDE2E2', dark: '#E5484D' },
  { id: 'green', light: '#E3F5E1', dark: '#2F9E44' },
  { id: 'purple', light: '#EDE3FB', dark: '#8B5CF6' },
  { id: 'orange', light: '#FFE8D6', dark: '#F76B15' },
  { id: 'teal', light: '#D9F2F0', dark: '#12B5A5' },
  { id: 'magenta', light: '#FBE0F0', dark: '#E64980' },
  { id: 'indigo', light: '#E0E7FF', dark: '#4C6EF5' },
  { id: 'brown', light: '#F0E6D9', dark: '#A16207' },
]

export function getTeamColorTones(colorId) {
  return TEAM_COLOR_PALETTE.find((entry) => entry.id === colorId) ?? TEAM_COLOR_PALETTE[0]
}

export function pickDefaultColorId(usedColorIds) {
  const usedSet = new Set(usedColorIds)
  const firstUnused = TEAM_COLOR_PALETTE.find((entry) => !usedSet.has(entry.id))
  return (firstUnused ?? TEAM_COLOR_PALETTE[0]).id
}

const DEFAULT_ICON_NAME = 'UsersFour'

export const TEAM_ICON_CATEGORIES = [
  {
    id: 'pessoas',
    label: 'Pessoas',
    icons: [
      { name: 'User', Icon: User },
      { name: 'Users', Icon: Users },
      { name: 'UsersFour', Icon: UsersFour },
      { name: 'UsersThree', Icon: UsersThree },
      { name: 'Handshake', Icon: Handshake },
      { name: 'Baby', Icon: Baby },
      { name: 'Student', Icon: Student },
      { name: 'GraduationCap', Icon: GraduationCap },
      { name: 'IdentificationBadge', Icon: IdentificationBadge },
      { name: 'Certificate', Icon: Certificate },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    icons: [
      { name: 'PencilRuler', Icon: PencilRuler },
      { name: 'Palette', Icon: Palette },
      { name: 'PaintBrush', Icon: PaintBrush },
      { name: 'Ruler', Icon: Ruler },
      { name: 'Pen', Icon: Pen },
      { name: 'Crop', Icon: Crop },
      { name: 'Image', Icon: Image },
      { name: 'PictureInPicture', Icon: PictureInPicture },
      { name: 'Camera', Icon: Camera },
      { name: 'FilmSlate', Icon: FilmSlate },
      { name: 'MagicWand', Icon: MagicWand },
    ],
  },
  {
    id: 'negocios',
    label: 'Negócios',
    icons: [
      { name: 'Briefcase', Icon: Briefcase },
      { name: 'Suitcase', Icon: Suitcase },
      { name: 'Buildings', Icon: Buildings },
      { name: 'Presentation', Icon: Presentation },
      { name: 'PresentationChart', Icon: PresentationChart },
      { name: 'ChartLine', Icon: ChartLine },
      { name: 'ChartLineUp', Icon: ChartLineUp },
      { name: 'ChartBar', Icon: ChartBar },
      { name: 'ChartPie', Icon: ChartPie },
      { name: 'Target', Icon: Target },
      { name: 'Trophy', Icon: Trophy },
      { name: 'Rocket', Icon: Rocket },
      { name: 'Lightbulb', Icon: Lightbulb },
      { name: 'Strategy', Icon: Strategy },
      { name: 'Kanban', Icon: Kanban },
      { name: 'Calendar', Icon: Calendar },
      { name: 'Clipboard', Icon: Clipboard },
      { name: 'Note', Icon: Note },
      { name: 'Files', Icon: Files },
      { name: 'Folder', Icon: Folder },
    ],
  },
  {
    id: 'tech',
    label: 'Tech',
    icons: [
      { name: 'Code', Icon: Code },
      { name: 'Terminal', Icon: Terminal },
      { name: 'Cpu', Icon: Cpu },
      { name: 'Desktop', Icon: Desktop },
      { name: 'Laptop', Icon: Laptop },
      { name: 'Database', Icon: Database },
      { name: 'CloudCheck', Icon: CloudCheck },
      { name: 'GitBranch', Icon: GitBranch },
      { name: 'Bug', Icon: Bug },
      { name: 'Robot', Icon: Robot },
      { name: 'Wrench', Icon: Wrench },
      { name: 'Gear', Icon: Gear },
      { name: 'Circuitry', Icon: Circuitry },
      { name: 'Plug', Icon: Plug },
      { name: 'WifiHigh', Icon: WifiHigh },
    ],
  },
  {
    id: 'comunicacao',
    label: 'Comunicação',
    icons: [
      { name: 'ChatCircle', Icon: ChatCircle },
      { name: 'Chat', Icon: Chat },
      { name: 'Envelope', Icon: Envelope },
      { name: 'Megaphone', Icon: Megaphone },
      { name: 'Broadcast', Icon: Broadcast },
      { name: 'Phone', Icon: Phone },
      { name: 'Headset', Icon: Headset },
      { name: 'Video', Icon: Video },
      { name: 'Microphone', Icon: Microphone },
      { name: 'SpeakerHigh', Icon: SpeakerHigh },
      { name: 'Globe', Icon: Globe },
    ],
  },
  {
    id: 'comercio',
    label: 'Comércio',
    icons: [
      { name: 'Storefront', Icon: Storefront },
      { name: 'ShoppingBag', Icon: ShoppingBag },
      { name: 'ShoppingCart', Icon: ShoppingCart },
      { name: 'Bank', Icon: Bank },
      { name: 'Wallet', Icon: Wallet },
      { name: 'CreditCard', Icon: CreditCard },
      { name: 'Coin', Icon: Coin },
      { name: 'Coins', Icon: Coins },
      { name: 'Money', Icon: Money },
      { name: 'Receipt', Icon: Receipt },
      { name: 'Truck', Icon: Truck },
      { name: 'Van', Icon: Van },
      { name: 'Airplane', Icon: Airplane },
      { name: 'Package', Icon: Package },
      { name: 'Scales', Icon: Scales },
      { name: 'Handbag', Icon: Handbag },
      { name: 'Factory', Icon: Factory },
    ],
  },
  {
    id: 'objetos',
    label: 'Objetos',
    icons: [
      { name: 'Recycle', Icon: Recycle },
      { name: 'Leaf', Icon: Leaf },
      { name: 'Tree', Icon: Tree },
      { name: 'Heart', Icon: Heart },
      { name: 'Star', Icon: Star },
      { name: 'Sparkle', Icon: Sparkle },
      { name: 'Compass', Icon: Compass },
      { name: 'MapPin', Icon: MapPin },
      { name: 'Flag', Icon: Flag },
      { name: 'Anchor', Icon: Anchor },
      { name: 'Hammer', Icon: Hammer },
      { name: 'Toolbox', Icon: Toolbox },
      { name: 'Cube', Icon: Cube },
      { name: 'Gift', Icon: Gift },
      { name: 'Balloon', Icon: Balloon },
      { name: 'Confetti', Icon: Confetti },
      { name: 'Books', Icon: Books },
      { name: 'BookOpen', Icon: BookOpen },
    ],
  },
]

const ICON_COMPONENTS_BY_NAME = TEAM_ICON_CATEGORIES.reduce((acc, category) => {
  category.icons.forEach(({ name, Icon }) => {
    acc[name] = Icon
  })
  return acc
}, {})

export function getTeamIconComponent(iconName) {
  return ICON_COMPONENTS_BY_NAME[iconName] ?? UsersFour
}

const KEYWORD_ICON_MAP = [
  { keywords: ['design'], iconName: 'PencilRuler' },
  { keywords: ['dev', 'desenvolv', 'engenharia', 'tech', 'tecno'], iconName: 'Code' },
  { keywords: ['venda', 'comercial', 'sales', 'negocio', 'negóci'], iconName: 'ShoppingCart' },
  { keywords: ['log', 'operac', 'operaç'], iconName: 'Truck' },
  { keywords: ['rh', 'pessoa', 'people', 'humano', 'gente'], iconName: 'GraduationCap' },
  { keywords: ['marketing', 'growth', 'crescimento'], iconName: 'Megaphone' },
]

export function guessTeamIconName(name) {
  const normalized = name.trim().toLowerCase()
  if (!normalized) return DEFAULT_ICON_NAME
  const match = KEYWORD_ICON_MAP.find((entry) =>
    entry.keywords.some((keyword) => normalized.includes(keyword)),
  )
  return match ? match.iconName : DEFAULT_ICON_NAME
}
